Numpy

In [3]:
import numpy as np 
a =np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [4]:
#creating a 1d array -- one dimenstion array
#is linear data structure where we store the elements in sequence

n1=np.array([1,2,3])

In [64]:
#Creating 2d array  
#It is an matrix like data structure wher data is stored in rows and columns.
import numpy as  np
b =np.array([[1,2,3],[4,5,6]])
type(b)
b.shape
b.dtype

dtype('int64')

In [30]:
import numpy as np
b =np.array([[1,2,3],[4,5,6]],dtype=int)
type(b)
print(b)


[[1 2 3]
 [4 5 6]]


b.dtype

In [25]:
import numpy as np
n=np.zeros((3,4))
n.shape


(3, 4)

In [ ]:
import numpy as np  
b =np.array([[1,2,3],[4,5,6]],dtype=float)
type(b)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [133]:
import numpy as np #array of a particular value
data =np.ones((5,5))
a=2
my_data=np.full((5,6),a)
print(my_data)

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [78]:
# create a identity matrix
import numpy as np
data=np.eye(4,6,0,dtype=int)
data

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [74]:
print(data)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [72]:
data.shape

(4, 5)

In [68]:
data.dtype

dtype('float64')

In [80]:

#create a numpy array with random values
import numpy as np
data=np.random.random((3,4))

In [81]:
data

array([[0.17087945, 0.17818647, 0.13837479, 0.28041391],
       [0.61922352, 0.73780894, 0.91161107, 0.24479754],
       [0.49826745, 0.71682535, 0.70267171, 0.66485912]])

In [106]:
#array of evenly spaced values--->specify the no of values required
import numpy as np 
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [104]:
print(data)

[ 1  3  5  7 10]


In [132]:
import numpy as np 
a=(2,3,4,56,11)
n =np.array(a)
n.resize((2,4))
print(n)

[[ 2  3  4 56]
 [11  0  0  0]]
