In [2]:
#Create an identity matrix of size 5.

import numpy as np
data=np.eye(5)
print(data)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#Reverse a NumPy array without using loops
import numpy as np
data=[2,4,6,67,100]
arr=np.array(data)
arr_1=arr[::-1]
print(arr_1)

[100  67   6   4   2]


array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [11]:
list=[1,2,4,6,7,9,0]
list[-1::]





[0]

In [1]:
list=[1,2,4,6,7,9,0]
list[-1::]

[0]

In [9]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

b=matrix[::-1,::-1]



In [10]:
print(b)

[[6 5 4]
 [3 2 1]]
